apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ratings-microservice
  template:
    metadata:
      labels:
        app: ratings-microservice
    spec:
      containers:
        - image: rsouser/ratings-microservice
          name: ratings-microservice
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: gke-rso-secrets
                  key: db_host
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: gke-rso-secrets
                  key: db_name
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: gke-rso-secrets
                  key: db_user
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: gke-rso-secrets
                  key: db_pass
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://${DB_HOST}/${DB_NAME}?user=${DB_USER}@rso-db&password=${DB_PASS}
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: ${DB_USER}
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              value: ${DB_PASS}
            - name: KUMULUZEE_CONFIG_CONSUL_AGENT
              value: http://10.244.1.21:8500
          ports:
            - containerPort: 8080
              name: server
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: ratings-service
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: ratings-microservice
