apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ratings-microservice
  template:
    metadata:
      labels:
        app: ratings-microservice
    spec:
      containers:
        - image: rsouser/ratings-microservice
          name: ratings-microservice
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: gke-rso-secrets
                  key: db_host
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: gke-rso-secrets
                  key: db_name
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: gke-rso-secrets
                  key: db_user
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: gke-rso-secrets
                  key: db_pass
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://rso-app-db.postgres.database.azure.com:5432/${DB_NAME}?user=dbuser@rso-app-db&password=${DB_PASS}
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: ${DB_USER}
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              value: ${DB_PASS}
            - name: KUMULUZEE_SERVER_HTTP_PORT
              value: "8004"
            - name: KUMULUZEE_ENV_NAME
              value: "dev"
            - name: KUMULUZEE_NAME
              value: "ratings-microservice"
            - name: KUMULUZEE_SERVER_BASEURL
              value: http://20.76.184.237/ratings-service/
            - name: KUMULUZEE_OPENAPIMP_UI_SPECIFICATIONSERVER
              value: http://20.76.184.237/ratings-service/
            - name: KUMULUZEE_OPENAPIMP_SERVERS
              value: http://20.76.184.237/ratings-service/
          ports:
            - containerPort: 8004
              name: server
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: ratings-service
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: ratings-microservice
